[package]
name = "sosia"
version = "0.0.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
serde_json = "1.0"
paperclip = { version = "0.8", features = ["actix4"] }
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
