apiVersion: v2
name: sosia
description: A Helm chart for Kubernetes
type: application
version: 0.0.0
appVersion: "1.16.0"
dependencies:
  - name: postgresql
    version: 16.0.1
    repository: https://charts.bitnami.com/bitnami
